var data = {
    "00": { choices : ["10: Vous allez vers le cimetiere", "11: Vous vous dirigez vers l'hôpital"],
            text : "Bienvenue a Mickey Town, la premiere personne que vous recontrez est le policier, il vous dit qu'en cas de soucis vous pouvez toujours venir vers lui, par exemple si vous avez qq un a mettre en sécurité, vous le remercier pour sa gentillesse et sa bienveillance et ",
            position : [50.544181465164954, 4.890834920911164, "la salle"],
            end: "No"},

    "10": { choices : ["20: Vous décidez d'aller avec eux", "21: Vous partez de votre coté"],
            text : "Vous entrez dans l'hôpital à l'entrée de mickey town et decidez de vous y reposer un peu, apres qq minutes, 3 freres: Lulu pipi et coco font leur apparition. Vous discutez un peu avec eux et au fil de la discussion, vous apprenez qu'ils ont rendez-vous avec minnie, ils vous proposent d'y aller avec eux",
            position : [50.543521852777644, 4.8927151282845305, "la grand place"],
            end: "No"},

    "11": {choices : ["00: Death"],
            text : "blablabla",
            position : [50.54488827288447, 4.891407001513431,"le pré"],
            end: "No"},

    "20": {choices : ["30: manger des pommes avec les 3 freres", "31: faire une sieste sous le pommier avec les 3 freres"],
            text : "Vous vous premmenez a mickey town avec les 3 freres, les rues sont plus belles les unes que les autres, les vieilles routes en pavé datant du moyen-age vous rappel l'innocence de votre enfance, bientot vous entrez dans un pré, vous passez a coté de quelques arbres fruitiers. Vous faites une pause en dessous d'un grand pommier, vous décidez de",
            position : [50.54488827288447, 4.891407001513431,"le cimetiere"],
            end: "No"},
    "21": {choices : ["32: Droite","33: Gauche"],
            text : "Vous vous premmenez a mickey town, seul, les rues sont plus belles les unes que les autres, les vieilles routes en pavé datant du moyen-age vous rappel l'innocence de votre enfance, bientot vous arrivez a une embouchure, une rue part a gauche, l'autre a droite, ces deux rues s'enfoncent plus profondément dans la rue et l'eclairage s'y fait plus mince, vous décidez quand même de vous engagez a",
            position : [50.5351671, 4.9159056,"le bois"],
            end: "No"},
    "30": {choices : ["40: Vous aidez Lulu a faire sortir la pomme en le retourant et en appuyant fermement sur son ventre","41: Vous courrez à l'hopital avec les 3 enfants"],
            text : "Vous mangez pomme apres pomme, elles sont delicieuses, vous ne savez plus vous arretez, elles sont croquantes et juteuses a la fois. Les enfants aussi en profitent enorment, peut-être un peu trop, en avalant une morceau de pomme trop gros Lulu s'etouffe. Les autres enfants sont pris de panique et se mettent a pleurer, vous devez faire quelque chose.",
            position : [50.543320502332485, 4.890984401885766, "la rue baugniet"],
            end: "No"},
    "31": {choices : [],
           text : "",
           position : [],
           end: "No"},
    "32": {choices : ["11: Vous mourrez, allez au cimetiere"],
            text : "Vous progressez dans la ruelle toujours plus sombre, cette partie de Mickey town est moins bien entretenue, vous trébuchez dans des pavés élevés par les arbres centenaires vous entourant, vous vous évanouissez. A votre reveil, vous tomber nez a nez avec Mickey, il vous regarde avec un grand sourire, vous regarder dans sa main, un couteau! Vous tentez de partir en courant mais il vous rattrape",
            position : [50.5351671, 4.9159056, "la salle"],
            end: "No"},
    "33": {choices : ["11: Vous mourrez, allez au cimetiere"],
            text : "Vous progressez dans la ruelle toujours plus sombre, cette partie de Mickey town est moins bien entretenue, vous trébuchez dans des pavés élevés par les arbres centenaires vous entourant, vous vous évanouissez. A votre reveil, vous tomber nez a nez avec Mickey, il vous regarde avec un grand sourire, vous regarder dans sa main, un couteau! Vous tentez de partir en courant mais il vous rattrape",
            position : [50.5351671, 4.9159056, "la salle"],
            end: "No"},
    "40": {choices : ["50: Allez chez minie"],
            text : "Ouf, Lulu crache le gros morceau de pomme, il est sauvé. Vous reprenez rapidement vos esprits et parvenez a calmer les enfants, vous vous dirigez ensemble chez minie.",
            position : [50.5351671, 4.9159056, "le cimetiere"],
            end: "No"},
    "50": {choices : [""],
            text : "",
            position : [50.5351671, 4.9159056, "la salle"],
            end: "No"},
}
  